name: grpcProxy-tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        target:
        - linux-amd64-grpcproxy
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: "1.16.3"
    - run: date
    - env:
        TARGET: ${{ matrix.target }}
      run: |
        echo "${TARGET}"
        case "${TARGET}" in
          linux-amd64-grpcproxy)
            PASSES='build grpcproxy'  CPU='4' COVER='false' RACE='true' ./test.sh 2>&1 | tee test.log
            ! egrep "(--- FAIL:|FAIL:|DATA RACE|panic: test timed out|appears to have leaked)" -B50 -A10 test.log
            ;;
